blog/urls.py
from django.urls import re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blog'

urlpatterns = [

    re_path(r'^$', views.post_list, name='post_list'),
    re_path(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    re_path(r'^(?P<postcategory_slug>[-\w]+)/$', views.post_list, name='post_list_by_category'),

]

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'
   
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

coupons/urls.py
from django.urls import path
from . import views
   
   
   
app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

details/urls.py
from django.urls import path, re_path
from . import views

app_name = "details"


urlpatterns = [
    re_path(r'^$', views.index, name="index"),
    re_path(r'^home/$', views.home, name="home"),
    re_path(r'^about/$', views.about, name="about"),
    re_path(r'^contact/$', views.contact, name="contact"),
    re_path(r'^frequent_question/$', views.fq, name="fq"),
    re_path(r'^privacy_policy/$', views.privacy_policy, name="privacy_policy"),


]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('details/', include('details.urls', namespace='details')),
    path('account/', include('account.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

details/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=False)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.
###coupons
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')



def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

details/views.py
from django.shortcuts import render
from shop.models import Category




def index(request):
    return render(request, "details/base.html",{})

def home(request):
        new_category = Category.objects.all()[:4]
        category_shortcut = Category.objects.all()[:10]
        num_category = Category.objects.all().count()
        return render(request, "details/home.html",{'new_category':new_category, 'category_shortcut':category_shortcut, 'num_category':num_category})

def about(request):
        return render(request, "details/about.html",{})

def contact(request):
        return render(request, "details/contact.html",{})

def fq(request):
        return render(request, "details/fq.html",{})

def privacy_policy(request):
        return render(request, "details/privacy_policy.html",{})

cart/templates/cart/detail.html
{% extends "details/base.html" %} {% load static %} {% load crispy_forms_tags %}{% block title %} سبد خرید {% endblock title %} {% block content %}

<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="{% url 'details:home' %}">خانه</a></li>
                        <li>سبد خرید</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--breadcrumbs area end-->

<!--shopping cart area start -->
<div class="cart_page_bg">
    <div class="container">
        <div class="shopping_cart_area">

            <div class="row">
                <div class="col-12">
                    <div class="table_desc">
                        <div class="cart_page table-responsive">
                            <table>
                                <thead>
                                    <tr>

                                        <th class="product_thumb">تصویر</th>
                                        <th class="product_name">محصول</th>
                                        <th class="product-price">قیمت</th>
                                        <th class="product_quantity">تعداد</th>
                                        <th class="product_total">جمع</th>
                                        <th class="product_remove">حذف</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for item in cart %} {% with product=item.product %}
                                    <tr>

                                        <td class="product_thumb">
                                            <a href="#"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'details/assets/img/product/product8.jpg' %}{% endif %}" alt=""></a>
                                        </td>
                                        <td class="product_name"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                                        <td class="product-price">{{product.price}}</td>
                                        <td class="product_quantity"><label></label>
                                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                {{ item.update_quantity_form.quantity|as_crispy_field }} {{ item.update_quantity_form.override|as_crispy_field }}
                                                <div class="cart_submit text-center">
                                                    <button type="submit">به روز رسانی سبد</button>
                                                </div>
                                                {% csrf_token %}
                                            </form>
                                        </td>
                                        <td class="product_total">{{item.total_price }}</td>
                                        <td class="product_remove"><a href="{% url 'cart:cart_remove' product.id %}"><i class="fa fa-trash-o"></i></a></td>



                                    </tr>
                                    {% endwith %} {% endfor %}
                                </tbody>
                            </table>
                            <!-- </div> -->
                            <!-- <div class="cart_submit"> -->
                            <!-- <button type="submit">به روز رسانی سبد</button> -->

                        </div>
                    </div>
                </div>
            </div>
            <!--coupon code area start-->
            <div class="coupon_area">
                <div class="row">

                    <div class="col-lg-6 col-md-6">
                        <div class="coupon_code left">
                            <h3>کد تخفیف</h3>
                            <div class="coupon_inner">

                                <form action="{% url 'coupons:apply' %}" method="POST">
                                    {% csrf_token %}
                                    <p>کد تخفیف خود را در صورت وجود وارد نمایید</p>
                                    {{ coupon_apply_form|crispy }}


                                    <!-- <input placeholder="کد تخفیف" type="text"> -->
                                    <button type="submit">اعمال کد تخفیف</button>
                                </form>
                            </div>
                        </div>
                    </div>



                    <div class="col-lg-6 col-md-6">
                        <div class="coupon_code right">
                            <h3>مجموع سبد</h3>
                            <div class="coupon_inner">
                                <div class="cart_subtotal">
                                    <p>جمع جزء</p>
                                    <p class="cart_amount">{{cart.get_total_price }}تومان</p>
                                </div>
                                <!-- <div class="cart_subtotal">
                                    <p>جمع کل</p>
                                    <p class="cart_amount">{{cart.get_total_price }}تومان</p>
                                </div> -->
                                <div class="cart_subtotal has-border">
                                    <p>جمع با تخفیف</p>
                                    <p class="cart_amount">{{ cart.get_total_price_after_discount|floatformat:2 }} تومان</p>
                                </div>
                                <div class="checkout_btn">

                                    <a href="{% url 'orders:order_create' %}">پرداخت</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--coupon code area end-->

        </div>
    </div>
</div>
<!--shopping cart area end -->



{% endblock content %}